services:
  - type: web
    name: codecritic-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: codecritic
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8000

  - type: web
    name: codecritic-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false